# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Desktop\Kuliah\Semester 5\Visual 3\Python\Python QT\uji_koding.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(578, 318)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 391, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_data = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.widget_data.setObjectName("widget_data")
        self.widget_data.setColumnCount(5)
        self.widget_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.widget_data.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.widget_data)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 68, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 10, 180, 113))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.editnpm = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.editnpm.setObjectName("editnpm")
        self.verticalLayout_3.addWidget(self.editnpm)
        self.editnama = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.editnama.setObjectName("editnama")
        self.verticalLayout_3.addWidget(self.editnama)
        self.editkelas = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.editkelas.setObjectName("editkelas")
        self.verticalLayout_3.addWidget(self.editkelas)
        self.editjurusan = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.editjurusan.setObjectName("editjurusan")
        self.verticalLayout_3.addWidget(self.editjurusan)
        self.edit_lahir = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edit_lahir.setObjectName("edit_lahir")
        self.verticalLayout_3.addWidget(self.edit_lahir)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(280, 40, 131, 82))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_insert = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_insert.setObjectName("btn_insert")
        self.verticalLayout_4.addWidget(self.btn_insert)
        self.btn_hapus_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_hapus_2.setObjectName("btn_hapus_2")
        self.verticalLayout_4.addWidget(self.btn_hapus_2)
        self.btn_filter = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btn_filter.setObjectName("btn_filter")
        self.verticalLayout_4.addWidget(self.btn_filter)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 270, 391, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_load = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout_5.addWidget(self.btn_load)
        self.labeldata_result = QtWidgets.QLabel(Form)
        self.labeldata_result.setGeometry(QtCore.QRect(280, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labeldata_result.setFont(font)
        self.labeldata_result.setObjectName("labeldata_result")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(410, 170, 121, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_cari_npm = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.edit_cari_npm.setObjectName("edit_cari_npm")
        self.horizontalLayout.addWidget(self.edit_cari_npm)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(410, 210, 121, 35))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_update = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout_6.addWidget(self.btn_update)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(410, 130, 151, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labe_apaNPM = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.labe_apaNPM.setObjectName("labe_apaNPM")
        self.verticalLayout_7.addWidget(self.labe_apaNPM)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.widget_data.horizontalHeaderItem(0)
        item.setText(_translate("Form", "npm"))
        item = self.widget_data.horizontalHeaderItem(1)
        item.setText(_translate("Form", "nama"))
        item = self.widget_data.horizontalHeaderItem(2)
        item.setText(_translate("Form", "kelas"))
        item = self.widget_data.horizontalHeaderItem(3)
        item.setText(_translate("Form", "jurusan"))
        item = self.widget_data.horizontalHeaderItem(4)
        item.setText(_translate("Form", "tanggal_lahir"))
        self.label.setText(_translate("Form", "NPM"))
        self.label_2.setText(_translate("Form", "Nama"))
        self.label_3.setText(_translate("Form", "kelas"))
        self.label_4.setText(_translate("Form", "jurusan"))
        self.label_5.setText(_translate("Form", "tanggal lahir"))
        self.btn_insert.setText(_translate("Form", "INSERT DATA"))
        self.btn_hapus_2.setText(_translate("Form", "HAPUS DATA"))
        self.btn_filter.setText(_translate("Form", "FILTER DATA"))
        self.btn_load.setText(_translate("Form", "LOAD DATA"))
        self.labeldata_result.setText(_translate("Form", "PENDING"))
        self.btn_update.setText(_translate("Form", "UPDATE DATA"))
        self.labe_apaNPM.setText(_translate("Form", "Ketik NPM yang ingin di update"))
        self.btn_insert.clicked.connect(self.masuk_data)
        self.btn_load.clicked.connect(self.data_load)
        self.btn_filter.clicked.connect(self.filter_data)
        self.btn_hapus_2.clicked.connect(self.hapus_data)
        self.btn_update.clicked.connect(self.update_data)

    def masuk_data(self):
        try:
            db = mc.connect(

            host ="localhost",
            user ="root",
            password ="",
            database ="db_kampus"
            )
            cursor = db.cursor()
            nama = self.editnama.text()
            npm = self.editnpm.text()
            kelas = self.editkelas.text()
            jurusan = self.editjurusan.text()
            tanggal_lahir = self.edit_lahir.text()
            sql = "INSERT INTO mahasiswa (npm,nama, kelas, jurusan, tanggal_lahir) VALUES (%s,%s,%s,%s,%s)"
            val = (npm,nama,kelas,jurusan,tanggal_lahir)
            cursor.execute(sql,val)
            db.commit()
            self.labeldata_result.setText("Data Berhasil Disimpan")

            self.editnama.setText("")
            self.editnpm.setText("")
            self.editkelas.setText("")
            self.editjurusan.setText("")
            self.edit_lahir.setText("")
        except mc.Error as e:
            self.labeldata_result.setText("Data Gagal")
            
    def data_load(self):
        try:
            db = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_kampus"
            )
            cursor = db.cursor()
            cursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
            result = cursor.fetchall()
            self.widget_data.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.widget_data.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.widget_data.setItem(row_number,column_number,
            QTableWidgetItem(str(data)))
            self.labeldata_result.setText("Data Berhasil Ditampilkan")
        except mc.Error as err:
            self.labeldata_result.setText("Data Gagal DiLoad")
            
    def filter_data(self):
        try:
            db = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_kampus"
            )
            cursor = db.cursor()
            npm = self.editnpm.text()
            sql = "SELECT * FROM mahasiswa WHERE npm=%s"
            val = (npm,)
            cursor.execute(sql,val)
            result = cursor.fetchall()
            self.widget_data.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.widget_data.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.widget_data.setItem(row_number,column_number,
            QTableWidgetItem(str(data)))
            self.labeldata_result.setText("Data Berhasil Di Filter")
            self.editnpm.setText("")
            
        except mc.Error as err:
            self.labeldata_result.setText("Data Gagal Di Filter")
            
    def hapus_data(self):
        try:
            db = mc.connect(

            host ="localhost",
            user ="root",
            password ="",
            database ="db_kampus"
            )
            cursor = db.cursor()
            npm = self.editnpm.text()
            sql = "DELETE FROM mahasiswa WHERE npm=%s"
            val = (npm,)
            cursor.execute(sql,val)
            db.commit()
            self.labeldata_result.setText("Data Berhasil Dihapus")
            self.editnpm.setText("")
            
        except mc.Error as e:
            self.labeldata_result.setText("Data Gagal Dihapus")
            
    def update_data(self):
        try:
            db = mc.connect(

            host ="localhost",
            user ="root",
            password ="",
            database ="db_kampus"
            )
            cursor = db.cursor()
            nama = self.editnama.text()
            npm = self.editnpm.text()
            kelas = self.editkelas.text()
            jurusan = self.editjurusan.text()
            tanggal_lahir = self.edit_lahir.text()
            which_npm = self.edit_cari_npm.text()
            sql = "UPDATE mahasiswa set npm =%s, nama=%s,kelas=%s,jurusan=%s,tanggal_lahir=%s WHERE npm=%s"
            val = (npm,nama,kelas,jurusan,tanggal_lahir,which_npm)
            cursor.execute(sql,val)
            db.commit()
            self.labeldata_result.setText("Data Berhasil Diupate")
            self.editnama.setText("")
            self.editnpm.setText("")
            self.editkelas.setText("")
            self.editjurusan.setText("")
            self.edit_lahir.setText("")
            self.edit_cari_npm.setText("")
            
        except mc.Error as e:
            self.labeldata_result.setText("Data Gagal Diupdate")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
